"""Explainable mapping from risk signals to controls and actions."""

from __future__ import annotations

CONTROL_MAP: dict[str, dict[str, str]] = {
    "no_mfa": {
        "category": "Identity & Access",
        "why_it_matters": "Compromised passwords often lead directly to account takeover.",
        "first_action": "Enable MFA on admin, email, cloud, and finance accounts.",
        "seven_day_action": "Enforce MFA policy and verify enrollment for all privileged users.",
        "investment_bucket": "MFA + Segmentation",
        "recommendation": "Prioritize MFA coverage before adding advanced controls.",
    },
    "shared_accounts": {
        "category": "Identity & Access",
        "why_it_matters": "Shared credentials remove accountability and hide misuse.",
        "first_action": "Replace shared admin logins with named user accounts.",
        "seven_day_action": "Disable shared accounts and document ownership for every privileged account.",
        "investment_bucket": "MFA + Segmentation",
        "recommendation": "Assign individual access and enforce strong authentication per user.",
    },
    "weak_passwords": {
        "category": "Identity & Access",
        "why_it_matters": "Weak passwords are easy to crack or reuse after breaches.",
        "first_action": "Enforce minimum password length and block known compromised passwords.",
        "seven_day_action": "Apply password policy with manager adoption and reset stale weak credentials.",
        "investment_bucket": "MFA + Segmentation",
        "recommendation": "Upgrade authentication policy and pair it with phishing-resistant MFA.",
    },
    "no_least_privilege": {
        "category": "Identity & Access",
        "why_it_matters": "Over-privileged users increase blast radius after compromise.",
        "first_action": "Review admin permissions and remove unnecessary privileged access.",
        "seven_day_action": "Implement role-based access controls and approval flow for privilege changes.",
        "investment_bucket": "MFA + Segmentation",
        "recommendation": "Tighten role scopes to reduce damage from a single compromised account.",
    },
    "stale_users": {
        "category": "Identity & Access",
        "why_it_matters": "Dormant accounts are often overlooked and can be abused silently.",
        "first_action": "Disable inactive users and contractors without current business need.",
        "seven_day_action": "Establish monthly joiner-mover-leaver review with ownership.",
        "investment_bucket": "MFA + Segmentation",
        "recommendation": "Automate offboarding and periodic access recertification.",
    },
    "public_api": {
        "category": "Infrastructure / Cloud",
        "why_it_matters": "Internet-facing APIs are common entry points for abuse and credential stuffing.",
        "first_action": "Require strong API authentication and rate limiting on public endpoints.",
        "seven_day_action": "Add API abuse alerts and rotate exposed keys or tokens.",
        "investment_bucket": "Detection + Response",
        "recommendation": "Harden public APIs with auth, quotas, and anomaly monitoring.",
    },
    "flat_network": {
        "category": "Infrastructure / Cloud",
        "why_it_matters": "Flat networks make lateral movement easier after initial access.",
        "first_action": "Separate admin systems, production workloads, and user devices.",
        "seven_day_action": "Implement network segmentation rules and validate blocked pathways.",
        "investment_bucket": "MFA + Segmentation",
        "recommendation": "Introduce practical segmentation around critical assets first.",
    },
    "no_segmentation": {
        "category": "Infrastructure / Cloud",
        "why_it_matters": "Lack of segmentation amplifies breach impact and recovery time.",
        "first_action": "Define security zones for admin, production, and internal services.",
        "seven_day_action": "Enforce segmentation policy with firewall and identity controls.",
        "investment_bucket": "MFA + Segmentation",
        "recommendation": "Apply minimum segmentation baseline across cloud and internal systems.",
    },
    "exposed_admin": {
        "category": "Infrastructure / Cloud",
        "why_it_matters": "Externally exposed admin panels are high-value targets.",
        "first_action": "Remove direct internet exposure for admin interfaces.",
        "seven_day_action": "Restrict admin paths to VPN or secure gateway with MFA.",
        "investment_bucket": "MFA + Segmentation",
        "recommendation": "Move admin access behind controlled, monitored channels.",
    },
    "unmanaged_cloud": {
        "category": "Infrastructure / Cloud",
        "why_it_matters": "Unmanaged cloud resources create drift and blind spots.",
        "first_action": "Inventory cloud resources and assign accountable owners.",
        "seven_day_action": "Enable cloud baseline checks for IAM, network, and storage misconfigurations.",
        "investment_bucket": "Detection + Response",
        "recommendation": "Adopt lightweight cloud posture checks and ownership tracking.",
    },
    "no_tested_backups": {
        "category": "Backups / Resilience",
        "why_it_matters": "Untested backups often fail during ransomware or outage recovery.",
        "first_action": "Run a restore test for one critical workload and document timing.",
        "seven_day_action": "Define recurring backup restore drills with pass/fail criteria.",
        "investment_bucket": "Backups + Recovery",
        "recommendation": "Treat restore testing as a required control, not a one-time task.",
    },
    "backups_not_isolated": {
        "category": "Backups / Resilience",
        "why_it_matters": "Online-only backups can be encrypted or deleted by attackers.",
        "first_action": "Enable immutable or offline backup copies for critical data.",
        "seven_day_action": "Apply backup isolation policy and verify retention settings.",
        "investment_bucket": "Backups + Recovery",
        "recommendation": "Isolate backup copies to protect recovery paths from compromise.",
    },
    "no_incident_plan": {
        "category": "Backups / Resilience",
        "why_it_matters": "Without a plan, teams lose time during incidents and make avoidable mistakes.",
        "first_action": "Create a one-page incident response playbook with owners.",
        "seven_day_action": "Run a short tabletop for account takeover and ransomware scenarios.",
        "investment_bucket": "Detection + Response",
        "recommendation": "Define incident roles and escalation triggers before the next event.",
    },
    "no_recovery_testing": {
        "category": "Backups / Resilience",
        "why_it_matters": "Recovery assumptions fail if failover and restore paths are never exercised.",
        "first_action": "Test system recovery for one business-critical service.",
        "seven_day_action": "Document RTO/RPO targets and validate against drill outcomes.",
        "investment_bucket": "Backups + Recovery",
        "recommendation": "Measure recovery readiness with recurring drills.",
    },
    "no_logging": {
        "category": "Monitoring / Detection",
        "why_it_matters": "No logs means incidents can persist without evidence or timeline.",
        "first_action": "Enable audit logging for identity, cloud, and endpoint events.",
        "seven_day_action": "Confirm retention and access controls for critical logs.",
        "investment_bucket": "Detection + Response",
        "recommendation": "Collect high-value logs first, then expand gradually.",
    },
    "no_alerting": {
        "category": "Monitoring / Detection",
        "why_it_matters": "Without alerting, suspicious activity is detected too late.",
        "first_action": "Configure alerts for admin login anomalies and privilege changes.",
        "seven_day_action": "Tune alert thresholds to reduce noise and validate on-call ownership.",
        "investment_bucket": "Detection + Response",
        "recommendation": "Start with a small set of high-signal alert rules.",
    },
    "no_centralized_monitoring": {
        "category": "Monitoring / Detection",
        "why_it_matters": "Siloed telemetry prevents fast triage across systems.",
        "first_action": "Centralize cloud and identity logs into one monitoring view.",
        "seven_day_action": "Build simple detection queries for account takeover and API abuse.",
        "investment_bucket": "Detection + Response",
        "recommendation": "Centralize visibility to improve response speed.",
    },
    "unpatched_dependencies": {
        "category": "Software / Supply Chain",
        "why_it_matters": "Known vulnerable dependencies are widely exploited.",
        "first_action": "Patch critical dependency vulnerabilities and remove abandoned packages.",
        "seven_day_action": "Establish weekly dependency update cadence with owner.",
        "investment_bucket": "Secure SDLC",
        "recommendation": "Treat dependency hygiene as ongoing maintenance, not ad hoc work.",
    },
    "no_dependency_scanning": {
        "category": "Software / Supply Chain",
        "why_it_matters": "Undetected vulnerabilities accumulate in builds and production images.",
        "first_action": "Enable dependency and container scanning in CI.",
        "seven_day_action": "Set severity thresholds and block builds on critical findings.",
        "investment_bucket": "Secure SDLC",
        "recommendation": "Automate dependency scanning to catch issues before release.",
    },
    "no_vendor_review": {
        "category": "Software / Supply Chain",
        "why_it_matters": "Third-party tools can introduce data handling and access risk.",
        "first_action": "List critical vendors and review security controls for each.",
        "seven_day_action": "Define lightweight vendor risk checklist for new purchases.",
        "investment_bucket": "Vendor Assurance",
        "recommendation": "Add basic vendor due diligence into procurement flow.",
    },
    "weak_cicd_controls": {
        "category": "Software / Supply Chain",
        "why_it_matters": "Weak CI/CD controls can allow malicious code or secret leakage.",
        "first_action": "Protect CI/CD with branch protections, MFA, and secret scanning.",
        "seven_day_action": "Require signed commits or approval checks for privileged pipelines.",
        "investment_bucket": "Secure SDLC",
        "recommendation": "Harden pipelines as production-critical infrastructure.",
    },
    "internet_facing_saas": {
        "category": "Infrastructure / Cloud",
        "why_it_matters": "Customer-facing SaaS platforms are continuously exposed to internet threats.",
        "first_action": "Document internet-facing assets and enforce baseline hardening controls.",
        "seven_day_action": "Review exposed services and verify auth, rate limiting, and patch status.",
        "investment_bucket": "Detection + Response",
        "recommendation": "Treat external attack surface as a standing risk and monitor it continuously.",
    },
    "baseline_controls_unspecified": {
        "category": "Security Governance",
        "why_it_matters": "Missing control details creates uncertainty and can hide high-impact gaps.",
        "first_action": "Confirm baseline controls for MFA, logging, backups, and incident response.",
        "seven_day_action": "Run a quick baseline checklist and record control owners and evidence.",
        "investment_bucket": "MFA + Segmentation",
        "recommendation": "Capture minimum-control evidence before assuming a low-risk posture.",
    },
}
