"""LLM reasoning and prompt construction."""

from __future__ import annotations

import socket
from typing import Any

from groq import Groq

from .config import SUPPORTED_MODELS

SYSTEM_PROMPT = (
    "You are Astraut Risk Reasoner from Astraut Solutions. You help SMEs think "
    "clearly about digital risk, trust and system design before small weaknesses "
    "become incidents. Core principles: Zero Trust thinking, AI-assisted risk "
    "reasoning, practical NIST/OWASP/CISA advice, tested backups, MFA everywhere, "
    "clear ownership in incidents, cloud resilience. Focus on small teams (5-50 "
    "people). Be practical, never scary. Structure output as: Overall Risk Score "
    "(1-10 with emoji), Top 3 Risks (short), Personalized Recommendations (Zero "
    "Trust steps first), 7-day Action Checklist, Suggested investment priorities "
    "(reference the 2025 matrix: start with MFA + segmentation, then detection, "
    "then advanced)."
)

EXPLAINER_PROMPT = (
    "You are a cybersecurity educator for SME teams. Explain topics clearly and "
    "practically in plain language. Include: definition, why it matters for SMEs, "
    "and 3 concrete actions. Keep it concise."
)


class ReasoningError(RuntimeError):
    """Base reasoning error."""


class InvalidInputError(ReasoningError):
    """Raised for invalid user input."""


class LLMAPIError(ReasoningError):
    """Raised when Groq API fails."""


class NetworkError(ReasoningError):
    """Raised for connectivity issues."""


def validate_company_description(company_description: str) -> None:
    """Validate user-provided company description."""
    text = (company_description or "").strip()
    if not text:
        raise InvalidInputError("Company description cannot be empty.")
    if len(text) < 10:
        raise InvalidInputError(
            "Description is too short. Provide at least a few details about your setup."
        )


def validate_model(model: str) -> None:
    """Validate selected model."""
    if model not in SUPPORTED_MODELS:
        allowed = ", ".join(sorted(SUPPORTED_MODELS))
        raise InvalidInputError(f"Invalid model '{model}'. Allowed values: {allowed}")


def build_assessment_messages(company_description: str) -> list[dict[str, str]]:
    """Build chat messages for assessment."""
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": company_description.strip()},
    ]


def build_explain_messages(topic: str) -> list[dict[str, str]]:
    """Build chat messages for concept explanation."""
    return [
        {"role": "system", "content": EXPLAINER_PROMPT},
        {
            "role": "user",
            "content": (
                f"Explain this cybersecurity concept for a small business team: {topic}."
            ),
        },
    ]


def request_completion(
    client: Groq,
    messages: list[dict[str, str]],
    model: str,
    temperature: float = 0.2,
) -> str:
    """Request completion from Groq and normalize errors."""
    try:
        response: Any = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=temperature,
        )
        content = response.choices[0].message.content if response.choices else None
        if not content:
            raise LLMAPIError("No response was generated by the model.")
        return content
    except (socket.timeout, socket.gaierror, ConnectionError, OSError) as exc:
        raise NetworkError(f"Network error while contacting Groq: {exc}") from exc
    except ReasoningError:
        raise
    except Exception as exc:
        raise LLMAPIError(f"Groq API request failed: {exc}") from exc
